# Generated by Django 5.2.7 on 2025-10-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explamation',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
