# Generated by Django 5.2.7 on 2025-10-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_product_explamation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='explamation',
            new_name='explanation',
        ),
    ]
