# Generated by Django 5.2.7 on 2025-10-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_explamation_product_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='explanation',
            new_name='explain',
        ),
    ]
