# Generated by Django 5.2.7 on 2025-10-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_rename_explanation_product_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
